### ISSUE TITLE
Почему передается только дата?

### ISSUE THREAD

**Issue by LanaRoz** [bluurn/comagic_client#15]
Почему передается только дата, без времени? 
В CoMagic, если не было указано время, к дате автоматом будет добавлено  00:00:00. 

Для примера, в одной из функций указан период: 
date_from: '2014-12-01', date_till: '2014-12-31'
Данные вернуться за период с 1 декабря по 30 декабря включительно. Это и ожидается? Нет путаницы или недопонимания?

**Comment by bluurn** [comment]
:beers:

**Comment by bluurn** [comment]
Какой формат даты ожидается на вашей стороне?

**Comment by LanaRoz** [comment]
тип timestamp
пример запроса: GET http://api.comagic.ru/api/v1/goal/?session_key=614c6619c516539664baede995bfa94f&site_id=2400&date_from=2014-12-01%2000:00:00&date_till=2014-12-31%2023:59:59

**Comment by bluurn** [comment]
исправлено
